import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CollectionOrderByWithRelationInputObjectSchema as CollectionOrderByWithRelationInputObjectSchema } from './objects/CollectionOrderByWithRelationInput.schema';
import { CollectionWhereInputObjectSchema as CollectionWhereInputObjectSchema } from './objects/CollectionWhereInput.schema';
import { CollectionWhereUniqueInputObjectSchema as CollectionWhereUniqueInputObjectSchema } from './objects/CollectionWhereUniqueInput.schema';
import { CollectionCountAggregateInputObjectSchema as CollectionCountAggregateInputObjectSchema } from './objects/CollectionCountAggregateInput.schema';
import { CollectionMinAggregateInputObjectSchema as CollectionMinAggregateInputObjectSchema } from './objects/CollectionMinAggregateInput.schema';
import { CollectionMaxAggregateInputObjectSchema as CollectionMaxAggregateInputObjectSchema } from './objects/CollectionMaxAggregateInput.schema';

export const CollectionAggregateSchema: z.ZodType<Prisma.CollectionAggregateArgs> = z.object({ orderBy: z.union([CollectionOrderByWithRelationInputObjectSchema, CollectionOrderByWithRelationInputObjectSchema.array()]).optional(), where: CollectionWhereInputObjectSchema.optional(), cursor: CollectionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CollectionCountAggregateInputObjectSchema ]).optional(), _min: CollectionMinAggregateInputObjectSchema.optional(), _max: CollectionMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CollectionAggregateArgs>;

export const CollectionAggregateZodSchema = z.object({ orderBy: z.union([CollectionOrderByWithRelationInputObjectSchema, CollectionOrderByWithRelationInputObjectSchema.array()]).optional(), where: CollectionWhereInputObjectSchema.optional(), cursor: CollectionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CollectionCountAggregateInputObjectSchema ]).optional(), _min: CollectionMinAggregateInputObjectSchema.optional(), _max: CollectionMaxAggregateInputObjectSchema.optional() }).strict();