import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkspaceMemberOrderByWithRelationInputObjectSchema as WorkspaceMemberOrderByWithRelationInputObjectSchema } from './objects/WorkspaceMemberOrderByWithRelationInput.schema';
import { WorkspaceMemberWhereInputObjectSchema as WorkspaceMemberWhereInputObjectSchema } from './objects/WorkspaceMemberWhereInput.schema';
import { WorkspaceMemberWhereUniqueInputObjectSchema as WorkspaceMemberWhereUniqueInputObjectSchema } from './objects/WorkspaceMemberWhereUniqueInput.schema';
import { WorkspaceMemberCountAggregateInputObjectSchema as WorkspaceMemberCountAggregateInputObjectSchema } from './objects/WorkspaceMemberCountAggregateInput.schema';
import { WorkspaceMemberMinAggregateInputObjectSchema as WorkspaceMemberMinAggregateInputObjectSchema } from './objects/WorkspaceMemberMinAggregateInput.schema';
import { WorkspaceMemberMaxAggregateInputObjectSchema as WorkspaceMemberMaxAggregateInputObjectSchema } from './objects/WorkspaceMemberMaxAggregateInput.schema';

export const WorkspaceMemberAggregateSchema: z.ZodType<Prisma.WorkspaceMemberAggregateArgs> = z.object({ orderBy: z.union([WorkspaceMemberOrderByWithRelationInputObjectSchema, WorkspaceMemberOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkspaceMemberWhereInputObjectSchema.optional(), cursor: WorkspaceMemberWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkspaceMemberCountAggregateInputObjectSchema ]).optional(), _min: WorkspaceMemberMinAggregateInputObjectSchema.optional(), _max: WorkspaceMemberMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkspaceMemberAggregateArgs>;

export const WorkspaceMemberAggregateZodSchema = z.object({ orderBy: z.union([WorkspaceMemberOrderByWithRelationInputObjectSchema, WorkspaceMemberOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkspaceMemberWhereInputObjectSchema.optional(), cursor: WorkspaceMemberWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkspaceMemberCountAggregateInputObjectSchema ]).optional(), _min: WorkspaceMemberMinAggregateInputObjectSchema.optional(), _max: WorkspaceMemberMaxAggregateInputObjectSchema.optional() }).strict();